[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"
lint.select = ["E","F","I","UP","B"]
exclude = ["venv", ".venv", ".tox", "build", "dist"]

[tool.mypy]
python_version = "3.11"
strict = true
warn_unused_configs = true
# Limit what mypy scans (speeds up + avoids vendor dirs)
files = ["app", "src", "tests"]

# Third-party libs that don't ship complete stubs:
[[tool.mypy.overrides]]
module = ["fastapi.*", "prometheus_fastapi_instrumentator.*", "fastapi.testclient"]
ignore_missing_imports = true
