---
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # ---- Install project deps, no matter how you declare them ----
      - name: Install project dependencies (robust)
        shell: bash
        run: |
          set -euxo pipefail
          if [ -f pyproject.toml ] && grep -q "^\[project\]" pyproject.toml; then
            # Editable install + test extras if defined
            pip install -e ".[test]" || true
          fi
          pip install -U fastapi pydantic pydantic-settings prometheus-fastapi-instrumentator requests uvicorn
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt || true
          fi

      - name: Show key packages (sanity check)
        run: |
          python - << 'PY'
          import importlib.util as iu
          for m in ["pydantic", "pydantic_settings", "fastapi"]:
              print(f"{m}: ", "OK" if iu.find_spec(m) else "MISSING")
          PY

      - name: Install tooling
        run: pip install pre-commit pytest pytest-cov

      - name: Run pre-commit (ruff, black, mypy)
        run: pre-commit run --all-files

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q --maxfail=1 --disable-warnings
