---
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project deps
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"
          pip install pre-commit  # if you prefer pre-commit separate

      - name: Run pre-commit (ruff, black, mypy)
        run: pre-commit run --all-files

      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings
